apiVersion: v2
name: kamu-molecule-bridge
description: Molecule Labs connector to Kamu
type: application
version: 0.5.1
appVersion: "0.5.1"
home: https://kamu.dev
icon: https://www.kamu.dev/images/kamu_logo_icon_bg_square.png
sources:
  - https://github.com/kamu-data/kamu-molecule-bridge-helm-charts
keywords:
  - desci
  - web3
  - molecule
  - kamu
  - opendatafabric
# TODO: Update this section after migrating repository to Molecule Protocol GH organization
# annotations:
#   "artifacthub.io/license": Apache-2.0
#   "artifacthub.io/links": |
#     - name: Chart Source
#       url: https://github.com/kamu-data/helm-charts
